### ISSUE TITLE
Improvement Suggestion-Add Comment Block!

### ISSUE THREAD

**Issue by MIngPAPA** [lingxz/er#3]
Hello, Ling!

I have a suggestion now! 

What about adding a comment block at the bottom of the blog with the help of GitHub issues, inspired by the project [gitment](https://github.com/imsun/gitment) and [this issue](https://github.com/imsun/gitment/issues/124).

**Comment by lingxz** [comment]
Hi Ming, 

I don't think I'll add comments for now because I wanted the theme to be quite minimal and personally I don't think a comments section is essential to a blog. Furthermore I think there are many commenting options out there (disqus / gitment / isso / talkyard etc) so I think it is better for people to add it if they want to. Thanks anyway!
